title: Sungjae Lee
email: sungjae@kookmin.ac.kr
description: >
  Personal homepage of James Sungjae Lee (Research Scientist, Engineer, Frontier)
baseurl: "/"
url: "sungjae.me"
twitter_username: ElonMusk 
github_username:  james-sungjae-lee

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->